task:
  name: vqa
  #debug: 1013
  chooser: cvpr # [null, cvpr, naacl]
  answers: 2000

model:
  name: nmn

  lstm_hidden: 1000
  layout_hidden: 100
  att_hidden: 100
  pred_hidden: 500

  combine_question: true
  att_normalization: local

opt:
  batch_size: 100
  iters: 30
  dropout: true
  multiclass: false

  rho: 0.95
  eps: 0.000001
  lr: 1
  clip: 10.0
